### ISSUE TITLE
[JOSS REVIEW] Minor build error in paper.md

### ISSUE THREAD

**Issue by katyhuff** [3dct/open_iA#36]
Whedon is having trouble with the current paper.md. 

```
PDF failed to compile for issue #1185 with the following error:

% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed

0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0
100 16 0 16 0 0 278 0 --:--:-- --:--:-- --:--:-- 280
Error producing PDF.
! Missing $ inserted.

$
l.358 T

Looks like we failed to compile the PDF
```

Please see comment here for what I believe to be the solution: 
https://github.com/3dct/open_iA/commit/e02c5481f2d2a14719a2c25c17f7733477d5f134#r32637253

**Comment by codeling** [comment]
Unfortunately that was not it. Not even removing the link completely fixes the issue

I'm pretty sure it's actually not a change on our side that causes the build to fail, as the paper.md that was used for the first build today was not changed since the last generated pdf (https://github.com/openjournals/joss-reviews/issues/1185#issuecomment-458211753). My local test build with pandoc also succeeds. I have no idea what the issue could be here. Has maybe something changed recently in the way that whedon builds the pdf? Or is there any way to get more comprehensive error output for the build?

**Comment by katyhuff** [comment]
Interesting! I'll look into it!

**Comment by codeling** [comment]
Should be fixed now! In the title in the metadata, underscores _must not_ be escaped, it seems.

**Comment by katyhuff** [comment]
wild. Nice catch!
